spring:
  datasource:
    platform: h2
    url: jdbc:h2:mem:ScansDB;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2-console
pool:
  size: 10